name: build-and-deploy

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_PAT }}

jobs:
  build-and-deploy:
    runs-on: github-runners-bstock84-zap2xml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate date tag
        id: date
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image with Kaniko
        uses: aevea/action-kaniko@master
        with:
          image: bstock84/gracenote
          tag: ${{ steps.date.outputs.TAG }}
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}
          cache: true
          cache_repo: bstock84/gracenote-cache