name: build-and-deploy

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_PAT }}

jobs:
  build-and-deploy:
    runs-on: github-runners-bstock84-zap2xml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate date tag
        id: date
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: DockerHub Login for Kaniko
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"${DOCKERHUB_USERNAME}\",\"password\":\"${DOCKERHUB_KEY}\"}}}" > /kaniko/.docker/config.json

      - name: Build and Push with Kaniko
        run: |
          /kaniko/executor \
            --context $(pwd) \
            --dockerfile $(pwd)/Dockerfile \
            --destination bstock84/gracenote:${{ steps.date.outputs.TAG }} \
            --destination bstock84/gracenote:latest \
            --skip-tls-verify
