name: build-and-deploy

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_PAT }}

jobs:
  build-and-deploy:
    runs-on: github-runners-bstock84-zap2xml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate date tag
        id: date
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${DOCKERHUB_KEY}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t bstock/gracenote:${{ steps.date.outputs.TAG }} .
          docker tag bstock/gracenote:${{ steps.date.outputs.TAG }} bstock/gracenote:latest

      - name: Push Docker image
        run: |
          docker push bstock/gracenote:${{ steps.date.outputs.TAG }}
          docker push bstock/gracenote:latest
