name: build-and-deploy

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_PAT }}

jobs:
  build-and-deploy:
    runs-on: github-runners-bstock84-zap2xml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required packages and img
        run: |
          sudo apt-get update
          sudo apt-get install -y uidmap
          curl -fsSL -o img https://github.com/genuinetools/img/releases/download/v0.5.11/img-linux-amd64
          chmod +x img
          sudo mv img /usr/local/bin/

      - name: Generate date tag
        id: date
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ env.DOCKERHUB_KEY }}" | img login --username "${{ env.DOCKERHUB_USERNAME }}" --password-stdin docker.io

      - name: Build and push image with Kaniko
        run: |
          curl -L https://github.com/GoogleContainerTools/kaniko/releases/download/v1.20.0/executor-linux-amd64 -o kaniko-executor
          chmod +x kaniko-executor
          ./kaniko-executor --context . \
                            --dockerfile Dockerfile \
                            --destination bstock84/gracenote:${{ steps.date.outputs.TAG }} \
                            --destination bstock84/gracenote:latest \
                            --skip-tls-verify
