name: build-and-deploy

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_PAT }}

jobs:
  build-and-deploy:
    runs-on: github-runners-bstock84-zap2xml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate date tag
        id: date
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: bstock84/gracenote:${{ steps.date.outputs.TAG }}
          cache-from: type=registry,ref=bstock84/gracenote-cache:buildcache
          cache-to: type=registry,ref=bstock84/gracenote-cache:buildcache,mode=max
