name: build-and-deploy

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_PAT }}

jobs:
  build-and-deploy:
    runs-on: github-runners-bstock84-zap2xml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate date tag
        id: date
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create Docker config
        run: |
          mkdir -p /tmp/.docker
          echo '{"auths":{"https://index.docker.io/v1/":{"username":"${{ env.DOCKERHUB_USERNAME }}","password":"${{ env.DOCKERHUB_KEY }}"}}}' > /tmp/.docker/config.json

      - name: Build and push Docker image with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:latest
        with:
          args: >-
            --context /github/workspace
            --dockerfile /github/workspace/Dockerfile
            --destination bstock84/gracenote:${{ steps.date.outputs.TAG }}
            --cache=true
            --cache-repo=bstock84/gracenote-cache
        env:
          DOCKER_CONFIG: /tmp/.docker